spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/iamreviewing?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 3141306947w666W@


mybatis-plus:
  type-aliases-package: domain.PO
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto