spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iamreviewing?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 3141306947w666W@
    type: com.alibaba.druid.pool.DruidDataSource



mybatis-plus:
  type-aliases-package: org.myself.iamreviewing.domain.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto